### ISSUE TITLE
LDAP Results limit

### ISSUE THREAD

**Issue by escamudo** [pemontto/n8n-nodes-ldap#4]
Because most AD are limited to 1000 results per request by default, there is a limitation in the limit field. Even if you put in more than 1000 rows, the result will always be limited to the AD maximum.
However, there is an option "-E" in ldapsearch that allows you to bypass the default paged results. If you supply to the ldap search command "-E pr=X/noprompt", where X is the new "pagedResults" value and 'noprompt', it will return all pages/results without additional user involvement.

Is it possible to implement the -E flag? Or change the limit field to use the -E option?

Btw, excellent project!!!

**Comment by pemontto** [comment]
@escamudo I've just added support for paging, can you test out `v0.1.7` and let me know if it works. It should appear as an update.
<img width="696" alt="SCR-20221025-q55" src="https://user-images.githubusercontent.com/939704/197845882-82bcb10c-60d3-4428-a1a9-33166f363c3b.png">

You will probably need to restart n8n to see the new option:
<img width="323" alt="SCR-20221025-q7e-2" src="https://user-images.githubusercontent.com/939704/197846420-c7937cec-f77d-44f3-925e-1dce9c6d6405.png">

**Comment by escamudo** [comment]
Huge thanks for responding so quickly!
The limit tag is still restricting the amount of results, most likely because something else has to be adjusted. Even if we clear the limit tag value, when saved, it automatically changes to 50. As a result, the "Page Size" is not taken into account.

![Untitled](https://user-images.githubusercontent.com/14899019/197881636-ea8e148a-2bae-4386-b870-f47ee376aefc.png)
![Untitled2](https://user-images.githubusercontent.com/14899019/197881640-9615f2ff-d496-447f-bed6-dece758ea53f.png)

**Comment by pemontto** [comment]
You need to set your page size smaller than your limit.

limit = how many results to return in total
Page size = how many results to pull in each request.

So if you wanted 7000 results with your current AD setup. Your limit would be 7000 and page size would be 1000 or lower.

**Comment by pemontto** [comment]
🤔 maybe I should default to a reasonable page size and let people increase/decrease, or remove it

**Comment by escamudo** [comment]
It's working perfectly!!! Thanks for all help!

Another thing, as a suggestion, and if possible, it is probably better to escape characters like "(" with backslash "\(" like a normal ldapsearch command rather than with hexadecimal character code "\28"

![with(illegal unescaped character)](https://user-images.githubusercontent.com/14899019/197997817-7f080fd6-d160-4825-ad23-756d30df6a1c.PNG)
![Capture](https://user-images.githubusercontent.com/14899019/197997833-57e3358f-beee-4885-a4a5-f892e3106a95.PNG)

**Comment by pemontto** [comment]
Was hoping I could do this trivially with the FilterParser, but it barfs at `Illegal unescaped character`. I can't think of a _trivial_ way to find the correct parens to escape. Happy for suggestions/PRs.

Closing this issue as resolved 👍
