### ISSUE TITLE
Handle special chars escaped with `\`

### ISSUE THREAD

**Issue by pemontto** [pemontto/n8n-nodes-ldap#6]
Based on https://github.com/pemontto/n8n-nodes-ldap/issues/4#issuecomment-1291796641 raised by @escamudo

Similar to ldapsearch we should add the convenience of escaping special chars (except NUL) with a backslash `\`. Special chars as defined by [RFC2254](https://www.rfc-editor.org/rfc/rfc2254) being `*()\`.

**Comment by pemontto** [comment]
@escamudo can you test backslash `\` escaping with v0.1.8?

<img width="927" alt="SCR-20221027-oqa" src="https://user-images.githubusercontent.com/939704/198350820-6ac53a90-dbc1-4d25-a1a0-0e109570a766.png">

**Comment by escamudo** [comment]
Hi @pemontto, it's working flawlessly! Huge thanks again, for all the support. For sure one of the best nodes for N8N.
